# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vlm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vlm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvlm.proto\x12\x03vlm\"M\n\x0cInferRequest\x12\x12\n\nscreenshot\x18\x01 \x01(\x0c\x12\x15\n\rskill_context\x18\x02 \x01(\t\x12\x12\n\nstate_hint\x18\x03 \x01(\t\"J\n\rInferResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"5\n\x13HealthCheckResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t2~\n\nVLMService\x12.\n\x05Infer\x12\x11.vlm.InferRequest\x1a\x12.vlm.InferResponse\x12@\n\x0bHealthCheck\x12\x17.vlm.HealthCheckRequest\x1a\x18.vlm.HealthCheckResponseB/Z-github.com/zerfx/new_jzd/internal/vlmpb;vlmpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vlm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/zerfx/new_jzd/internal/vlmpb;vlmpb'
  _globals['_INFERREQUEST']._serialized_start=18
  _globals['_INFERREQUEST']._serialized_end=95
  _globals['_INFERRESPONSE']._serialized_start=97
  _globals['_INFERRESPONSE']._serialized_end=171
  _globals['_HEALTHCHECKREQUEST']._serialized_start=173
  _globals['_HEALTHCHECKREQUEST']._serialized_end=193
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=195
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=248
  _globals['_VLMSERVICE']._serialized_start=250
  _globals['_VLMSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
