// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/vlm.proto

package vlmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Screenshot    []byte                 `protobuf:"bytes,1,opt,name=screenshot,proto3" json:"screenshot,omitempty"`                         // PNG 格式截图
	SkillContext  string                 `protobuf:"bytes,2,opt,name=skill_context,json=skillContext,proto3" json:"skill_context,omitempty"` // Skill 文件正文（注入 VLM prompt）
	StateHint     string                 `protobuf:"bytes,3,opt,name=state_hint,json=stateHint,proto3" json:"state_hint,omitempty"`          // 当前 FSM 状态（辅助推理）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_proto_vlm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vlm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_proto_vlm_proto_rawDescGZIP(), []int{0}
}

func (x *InferRequest) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *InferRequest) GetSkillContext() string {
	if x != nil {
		return x.SkillContext
	}
	return ""
}

func (x *InferRequest) GetStateHint() string {
	if x != nil {
		return x.StateHint
	}
	return ""
}

type InferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`                                 // 推理结果（JSON 字符串）
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`                       // 置信度（0.0-1.0）
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 错误信息（空字符串表示无错误）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferResponse) Reset() {
	*x = InferResponse{}
	mi := &file_proto_vlm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferResponse) ProtoMessage() {}

func (x *InferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vlm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferResponse.ProtoReflect.Descriptor instead.
func (*InferResponse) Descriptor() ([]byte, []int) {
	return file_proto_vlm_proto_rawDescGZIP(), []int{1}
}

func (x *InferResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *InferResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InferResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_vlm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vlm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_vlm_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`    // VLM 模型是否已就绪
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // vlm_server 版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_vlm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vlm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_vlm_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_vlm_proto protoreflect.FileDescriptor

const file_proto_vlm_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/vlm.proto\x12\x03vlm\"r\n" +
	"\fInferRequest\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x01 \x01(\fR\n" +
	"screenshot\x12#\n" +
	"\rskill_context\x18\x02 \x01(\tR\fskillContext\x12\x1d\n" +
	"\n" +
	"state_hint\x18\x03 \x01(\tR\tstateHint\"l\n" +
	"\rInferResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12HealthCheckRequest\"E\n" +
	"\x13HealthCheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2~\n" +
	"\n" +
	"VLMService\x12.\n" +
	"\x05Infer\x12\x11.vlm.InferRequest\x1a\x12.vlm.InferResponse\x12@\n" +
	"\vHealthCheck\x12\x17.vlm.HealthCheckRequest\x1a\x18.vlm.HealthCheckResponseB/Z-github.com/zerfx/new_jzd/internal/vlmpb;vlmpbb\x06proto3"

var (
	file_proto_vlm_proto_rawDescOnce sync.Once
	file_proto_vlm_proto_rawDescData []byte
)

func file_proto_vlm_proto_rawDescGZIP() []byte {
	file_proto_vlm_proto_rawDescOnce.Do(func() {
		file_proto_vlm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vlm_proto_rawDesc), len(file_proto_vlm_proto_rawDesc)))
	})
	return file_proto_vlm_proto_rawDescData
}

var file_proto_vlm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_vlm_proto_goTypes = []any{
	(*InferRequest)(nil),        // 0: vlm.InferRequest
	(*InferResponse)(nil),       // 1: vlm.InferResponse
	(*HealthCheckRequest)(nil),  // 2: vlm.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: vlm.HealthCheckResponse
}
var file_proto_vlm_proto_depIdxs = []int32{
	0, // 0: vlm.VLMService.Infer:input_type -> vlm.InferRequest
	2, // 1: vlm.VLMService.HealthCheck:input_type -> vlm.HealthCheckRequest
	1, // 2: vlm.VLMService.Infer:output_type -> vlm.InferResponse
	3, // 3: vlm.VLMService.HealthCheck:output_type -> vlm.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_vlm_proto_init() }
func file_proto_vlm_proto_init() {
	if File_proto_vlm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vlm_proto_rawDesc), len(file_proto_vlm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vlm_proto_goTypes,
		DependencyIndexes: file_proto_vlm_proto_depIdxs,
		MessageInfos:      file_proto_vlm_proto_msgTypes,
	}.Build()
	File_proto_vlm_proto = out.File
	file_proto_vlm_proto_goTypes = nil
	file_proto_vlm_proto_depIdxs = nil
}
